/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _big_bomb_boom_h_
#define _big_bomb_boom_h_
//---------------------------------------------------------------------------------
extern const unsigned char big_bomb_boom[];
extern const int big_bomb_boom_size;
//---------------------------------------------------------------------------------
#endif //_big_bomb_boom_h_
//---------------------------------------------------------------------------------
