/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _font_console_h_
#define _font_console_h_
//---------------------------------------------------------------------------------
extern const unsigned char font_console[];
extern const int font_console_size;
//---------------------------------------------------------------------------------
#endif //_font_console_h_
//---------------------------------------------------------------------------------
